repositories:
  - name: coredns
    url: https://coredns.github.io/helm

releases:
  - name: coredns
    namespace: coredns
    chart: coredns/coredns
    version: "~1"
    missingFileHandler: Warn
    values:
      - values/coredns.yaml
