---
# Source: metrics-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
    helm.sh/chart: metrics-server-5.10.5
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/instance: metrics-server
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metrics-server
        helm.sh/chart: metrics-server-5.10.5
        app.kubernetes.io/instance: metrics-server
        app.kubernetes.io/managed-by: Helm
    spec:
      
      serviceAccountName: metrics-server
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: metrics-server
                    app.kubernetes.io/instance: metrics-server
                namespaces:
                  - "metrics-server"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 65534
      containers:
        - name: metrics-server
          image: k8s.gcr.io/metrics-server/metrics-server:v0.5.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: https
              containerPort: 8443
          args:
            - --secure-port=8443
            - --cert-dir=/tmp
            - --kubelet-insecure-tls
            - --kubelet-preferred-address-types=InternalIP,Hostname
            - --kubelet-use-node-status-port
            - --metric-resolution=15s
          resources:
            limits: {}
            requests: {}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: https
              scheme: HTTPS
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: https
              scheme: HTTPS
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpdir
      volumes:
        - emptyDir: {}
          name: tmpdir
