---
# Source: metrics-server/templates/metrics-server-crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
    helm.sh/chart: metrics-server-5.10.10
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-server
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: metrics-server
