---
# Source: metrics-server/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  labels:
    app.kubernetes.io/name: metrics-server
    helm.sh/chart: metrics-server-5.10.7
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
