---
# Source: metrics-server/templates/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: metrics-server

  labels:
    app.kubernetes.io/name: metrics-server
    helm.sh/chart: metrics-server-5.10.13
    app.kubernetes.io/instance: metrics-server
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      nodePort: null
  selector:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/instance: metrics-server
