apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-secret
    namespace: argocd
spec:
    suspend: false
    secretTemplates:
        - name: argocd-secret
          stringData:
            webhook.github.secret: ENC[AES256_GCM,data:IaJ4I08frHkr7SZsQmrp4IGdRonVHY2fXHzfovu6TR0=,iv:lauoLRQYHSxWh0Cq4P9PAHnAadrynaD9oK1OtQemQgA=,tag:JDYhC3Y2aJRCfL7j4a3FNQ==,type:str]
            server.secretkey: ENC[AES256_GCM,data:5K7jQBlvWywlYJl8S6Et1DJaByuiC+kpUWHBn4FZCTQiQZDsjr1KVngVBZE=,iv:bYHKXSxU8dmjh2/j7hezht471qJyQ9VozeVix2soQeU=,tag:H2/L3F1e+NjeGGWAHOnpBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZCtXRk9VNDV0Nnc2Y0dp
            Q1p4OUM0eCtxQUFicGNabGVxOStaNmcxNFRrCkM5b050anF2c01ORVFWejFEclZJ
            NDg5NVhoNmlKZk9MYWN4ZDBvM1dRbkEKLS0tIGwxYjZFc3lQVXhsQXEzdnZlRHl6
            eHRmQndtMU5OUnBZNUx4dFVkOHBSSEUK7qs1rgp+JrDPAru5F9k43n9qmawVDb1v
            IQXJx3jPB821elb1RDq20wlPK/4jkE3q/o2CzjBf3+qen5m1RPoHBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-12T20:29:19Z"
    mac: ENC[AES256_GCM,data:BawZWVS+2sOBnpBAJu+v6Hds8qHi66HeN5a4rq67/GZkNo0XXs7TYJyNhDfNxiAsFPJdfospUYAkYpO+jvQE7DW06qbLq2Lwq+pNSPaBWWEJdD91o8qYhvmhWmdn6kkSXDd/EdiM+Xh1lv76aI4/QDwxQCNO9msTVKt5PVUkxsI=,iv:+U29blI40THVoE5YM6FdIOXSvyxmBcURXbcYyAkimN0=,tag:iwQbbgOqMPg5tfoWj4x89w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
