apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-secret
    namespace: argocd
spec:
    suspend: false
    secretTemplates:
        - name: argocd-secret
          stringData:
            webhook.github.secret: ENC[AES256_GCM,data:IaJ4I08frHkr7SZsQmrp4IGdRonVHY2fXHzfovu6TR0=,iv:lauoLRQYHSxWh0Cq4P9PAHnAadrynaD9oK1OtQemQgA=,tag:JDYhC3Y2aJRCfL7j4a3FNQ==,type:str]
            server.secretkey: ENC[AES256_GCM,data:5K7jQBlvWywlYJl8S6Et1DJaByuiC+kpUWHBn4FZCTQiQZDsjr1KVngVBZE=,iv:bYHKXSxU8dmjh2/j7hezht471qJyQ9VozeVix2soQeU=,tag:H2/L3F1e+NjeGGWAHOnpBw==,type:str]
            dex.github.client.id: ENC[AES256_GCM,data:lWJcor4mKdCzn4z8NOI40vXF3iA=,iv:i0KlOIyTN17yM698oenBY8v+XRTNi/V52jw4aUohmOQ=,tag:XGxMqKPDTdjxcU4wMh4+5w==,type:str]
            dex.github.client.secret: ENC[AES256_GCM,data:TZLaBuTAVUcwy9ktC1/fo1suygsc70aBU54PFOK5NescT/0Os/se+A==,iv:KSSfE7+obfW6eYQt53pao02tFx7cGN7nR+kK31zTo9k=,tag:SFPMuQkouF+9aLqJZDRK4g==,type:str]
            dex.github.organization: ENC[AES256_GCM,data:zVeBZio490E=,iv:COm3+EuugbRc85ur8AGr2ezcID4mlwRvnTRURp4Z9us=,tag:X4jySgA3Dkla/udGFR1cOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZCtXRk9VNDV0Nnc2Y0dp
            Q1p4OUM0eCtxQUFicGNabGVxOStaNmcxNFRrCkM5b050anF2c01ORVFWejFEclZJ
            NDg5NVhoNmlKZk9MYWN4ZDBvM1dRbkEKLS0tIGwxYjZFc3lQVXhsQXEzdnZlRHl6
            eHRmQndtMU5OUnBZNUx4dFVkOHBSSEUK7qs1rgp+JrDPAru5F9k43n9qmawVDb1v
            IQXJx3jPB821elb1RDq20wlPK/4jkE3q/o2CzjBf3+qen5m1RPoHBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-13T00:46:20Z"
    mac: ENC[AES256_GCM,data:BexvsfDERo8/kdrj/ZuQWUh+B/AUIr+EliLKNW2Bb9nkYiHpVnAe9vw9Be/6YO9VC08EHIefjk/p+LQrv9M3ANe4t4aH5aXKqOTl3naqTqtMe82jUN4wSQWTq98rdMqIeKtiB7qJhqAR0+q0H4fsXgJ5ilt9pipwFXJ0cCw8oH0=,iv:OFfdim0D3L1VgnwqK5LURjA6h7NctVF9HgIJAb33K4k=,tag:wD8PGrjv/H+2U40M44XOdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
