apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minecraft-rcon-credentials
    namespace: minecraft
spec:
    suspend: false
    secretTemplates:
        - name: minecraft-rcon-credentials
          type: kubernetes.io/basic-auth
          stringData:
            username: ""
            password: ENC[AES256_GCM,data:1OPwK9I6yGmQE/j7qWEmYug++D76EXwZblRRgzeJ,iv:cU/L4pN7nFmzVD+7jE4rMq0zXJiO5Eruq0U0dTCDdV4=,tag:wvuT5sNE5+xuXzu6+i1K/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByREpjQzluRGxVYVp4aFJY
            OXVKVDh2dFFiY0xIY3VhWTF1OGMzSFBydG1JCjdWc0NRUjl4aFNMTStoK2p1QVVE
            RExaeGhiZy90TUdWOVdMKzhUb1FrWWsKLS0tIFpueFlJTTlNREp4VnpZYk9zSUJr
            bXRISEZ1NS9Jd2tqbENpYUJWeUtMdzQKGDcNlsohA2xJ4zuaB6afb93LiU+5YNUk
            tzGoYtwdj4Su3gl7BNiB7ASMIimQ1e33lVBNHhQTCD4fPWbQX4ZBvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-07T05:12:14Z"
    mac: ENC[AES256_GCM,data:U40zN4Q+hP1qRV78RSFGk1JC9n2U1ZcOlEDXmKR6X4bmDUW2w5/RHW7ILmT0hGP6rq3Mix5GC3kHK9le7Jnl27RMdP8qSWMPrOcvqBCWjubv6OLCgnBqX1sOZ6DyOutb+bCwRhuYXNuwvkXxJP9mW6OA7jokW5rL5aeQaiiuGRE=,iv:3J6GoBwBvD/xoTezU0y4ziRiLonY3csURxr9A9/9tG0=,tag:xRIHYnNXN7slaZp3XjpI4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
