apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/moopholo/homelab-kubernetes.git
        revision: main
        # files:
        #   - path: apps/**/deploy/targets/*.yaml
        directories:
          - path: apps/*
          - path: apps/coredns
            exclude: true
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/moopholo/homelab-kubernetes.git
        targetRevision: main
        path: "{{path}}/deploy/releases/local"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=background
          - PruneLast=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3
          backoff:
            duration: 15s
            factor: 3
