---
# Source: snapshot-controller/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-controller
  labels:
    helm.sh/chart: snapshot-controller-1.2.1
    app.kubernetes.io/name: snapshot-controller
    app.kubernetes.io/instance: snapshot-controller
    app.kubernetes.io/version: "v4.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
      app.kubernetes.io/instance: snapshot-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snapshot-controller
        app.kubernetes.io/instance: snapshot-controller
    spec:
      serviceAccountName: snapshot-controller
      securityContext:
        {}
      containers:
        - name: snapshot-controller
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "k8s.gcr.io/sig-storage/snapshot-controller:v4.2.1"
          imagePullPolicy: IfNotPresent
          args:
            - --leader-election
            - --leader-election-namespace=$(NAMESPACE)
            - --http-endpoint=:8080
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {}
