---
# Source: prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-node-exporter
  namespace: prometheus
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-2.2.0
    release: "prometheus-node-exporter"
    heritage: "Helm"
  annotations:
    {}
imagePullSecrets:
  []
