---
# Source: velocity/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velocity
  namespace: minecraft
  labels:
    helm.sh/chart: velocity-0.3.0
    app.kubernetes.io/name: velocity
    app.kubernetes.io/instance: velocity
    app.kubernetes.io/version: "3.1.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
automountServiceAccountToken: false
secrets:
  []
imagePullSecrets:
  []
