---
# Source: cert-manager-tls/templates/certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-thedixon-net
  namespace: argocd
  labels:
    helm.sh/chart: cert-manager-tls-1.0.1
    app.kubernetes.io/name: argocd-thedixon-net
    app.kubernetes.io/instance: argocd-ui-certificate
    app.kubernetes.io/managed-by: Helm
spec:
  dnsNames:
  - argocd.thedixon.net
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager-webhook-dnsimple-production
  secretName: argocd-thedixon-net-tls
