image:
  name: arm64v8/traefik

deployment:
  enabled: true

ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: true

service:
  enabled: true
  type: NodePort

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    nodePort: 30090
  web:
    port: 8000
    nodePort: 32080
  websecure:
    port: 8443
    nodePort: 32443

logs:
  access:
    enabled: true
    format: json
    filters:
      statuscodes: 400-599
      retryattempts: true
