image:
  name: arm64v8/traefik

deployment:
  enabled: true
  kind: DaemonSet

ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: true

service:
  enabled: false

hostNetwork: true
ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
  web:
    port: 8000
    hostPort: 8000
  websecure:
    port: 8443
    hostPort: 8443

logs:
  access:
    enabled: true
    format: json
    filters:
      statuscodes: 400-599
      retryattempts: true
