image:
  name: arm64v8/traefik

deployment:
  enabled: true
  kind: DaemonSet

ingressClass:
  enabled: true
  isDefaultClass: true

ingressRoute:
  dashboard:
    enabled: true

service:
  enabled: true
  type: NodePort

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    hostPort: 9000
  web:
    port: 8000
    hostPort: 80
  websecure:
    port: 8443
    hostPort: 443
  minecraft:
    port: 25565
    hostPort: 25565
  # minecraft-bedrock:
  #   port: 19132
  #   hostPort: 19132
  #   protocol: UDP

logs:
  access:
    enabled: true
    format: json
    filters:
      statuscodes: 400-599
      retryattempts: true
