---
# Source: pomerium/templates/authorize-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pomerium-authorize
    helm.sh/chart: pomerium-28.0.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/component: authorize
  name: pomerium-authorize
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pomerium-authorize
      app.kubernetes.io/instance: pomerium
  template:
    metadata:
      annotations:
        checksum: 8d78849114a6dd9730fc418787ef9e1a3831554924bcc5a5aacdfadb994ae093
      labels:
        app.kubernetes.io/name: pomerium-authorize
        helm.sh/chart: pomerium-28.0.2
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: pomerium
    spec:
      containers:
      - name: pomerium
        image: pomerium/pomerium:v0.16.2
        imagePullPolicy: IfNotPresent
        args:
          - --config=/etc/pomerium/config.yaml
        env:        
        - name: CERTIFICATE_FILE
          value: /pomerium/tls/tls.crt
        - name: CERTIFICATE_KEY_FILE
          value: /pomerium/tls/tls.key
        - name: SERVICES
          value: authorize
        - name: SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: pomerium-signing-key
              key: signing-key        
        envFrom:
          - secretRef:
              name: pomerium-shared-env
        ports:
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 9090
            name: metrics
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: https
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: https
        resources:
          {}
        volumeMounts:
          - mountPath: /etc/pomerium/
            name: config
          - mountPath: /pomerium/tls
            name: service-tls
          - mountPath: /pomerium/ca
            name: ca-tls
      serviceAccountName: pomerium-authorize
      volumes:
        - name: config
          secret:
            secretName: pomerium
        - name: ca-tls
          secret:
            secretName: pomerium-tls
            optional: true
        - name: service-tls
          secret:
            secretName: pomerium-tls
            optional: true
