---
# Source: pomerium/templates/cache-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pomerium-cache
  labels:
    app.kubernetes.io/name: pomerium-cache
    helm.sh/chart: pomerium-25.0.0
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cache
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: pomerium-databroker
    app.kubernetes.io/instance: pomerium
