---
# Source: pomerium/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pomerium-authenticate
  labels:
    app.kubernetes.io/name: pomerium-authenticate
    helm.sh/chart: pomerium-25.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/component: authenticate
  annotations:
---
# Source: pomerium/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pomerium-authorize
  labels:
    app.kubernetes.io/name: pomerium-authorize
    helm.sh/chart: pomerium-25.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/component: authorize
  annotations:
---
# Source: pomerium/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pomerium-databroker
  labels:
    app.kubernetes.io/name: pomerium-databroker
    helm.sh/chart: pomerium-25.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/component: databroker
  annotations:
---
# Source: pomerium/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pomerium-proxy
  labels:
    app.kubernetes.io/name: pomerium-proxy
    helm.sh/chart: pomerium-25.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/component: proxy
  annotations:
