---
# Source: pomerium/templates/signing-key-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: pomerium
    helm.sh/chart: pomerium-25.0.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: pomerium
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook: pre-install
  name: pomerium-signing-key
type: Opaque
data:
  signing-key: TFMwdExTMUNSVWRKVGlCRlF5QlFVa2xXUVZSRklFdEZXUzB0TFMwdENrMUlZME5CVVVWRlNVRXliMHAwVGpKRE1IQTJXRlp3WW04NWNuRnZlVkZFUW1GVU1tRnZUMjEwWTBJdk1ERkVXbUpRYUV4dlFXOUhRME54UjFOTk5Ea0tRWGRGU0c5VlVVUlJaMEZGVUVsaE0yMDNVbWRZZHl0MlZqWXdRMGhsUTNORWRteHlWMEpPTm1WeUt6WXpNazUxTjBGbWFUZ3hkbW8wWnl0Rk4xZEtSZ3A1T1hKc1RtVnlSa2t5Wm5GdGJYaHhTVTB5WjJKSVdTODRWRFUwUjBGSmNWaFJQVDBLTFMwdExTMUZUa1FnUlVNZ1VGSkpWa0ZVUlNCTFJWa3RMUzB0TFFvPQ==
