---
# Source: pomerium/templates/signing-key-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: pomerium
    helm.sh/chart: pomerium-28.0.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: pomerium
  annotations:
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook: pre-install
  name: pomerium-signing-key
type: Opaque
data:
  signing-key: TFMwdExTMUNSVWRKVGlCRlF5QlFVa2xXUVZSRklFdEZXUzB0TFMwdENrMUlZME5CVVVWRlNVMU5lVVp1VjNJdlVrY3lRM2Q2T1VJeFpWSmxRa1p2UlRnd1NsVkZhWE55V1VFeWRsRnVRbVprYldKdlFXOUhRME54UjFOTk5Ea0tRWGRGU0c5VlVVUlJaMEZGZG5wM1VuTnJRVFY0Y1hWMk56VjBTMEZaTDBjMFkyaEdRWFJ0U1hOdFdsSkRlVXQ1ZGtOM2FUZGFOV1ZWYkRCeVpFOXpXZ3ByUm5OUk5DOTNPRUZvYmxvM1VpODJaMms1VUdGd05DOVRTbW96UldKUmRtMUJQVDBLTFMwdExTMUZUa1FnUlVNZ1VGSkpWa0ZVUlNCTFJWa3RMUzB0TFFvPQ==
