routes:
  minecraft:
    tcp: true
    entryPoints: [minecraft]
    routes:
      - match: HostSNI(`*`)
        kind: Rule
        services:
          - name: minecraft-minecraft
            port: minecraft
