repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik
  - name: moopholo
    url: https://helm.monetact.net

apiVersions:
  - "networking.k8s.io/v1/IngressClass"

values:
  - default-certificate:
      enabled: true

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: "~10"
    missingFileHandler: Warn
    values:
      - values/traefik.yaml

  - name: traefik-default-certificate
    namespace: traefik
    chart: moopholo/cert-manager-tls
    version: "~1"
    condition: default-certificate.enabled
    missingFileHandler: Warn
    values:
      - values/traefik-default-certificate.yaml.gotmpl
      - global:
          labels:
            app.kubernetes.io/part-of: traefik
          annotations:
            argocd.argoproj.io/sync-wave: "1"

  - name: traefik-default-certificate-store
    namespace: traefik
    chart: moopholo/traefik-custom-resources
    version: "~0"
    condition: default-certificate.enabled
    missingFileHandler: Warn
    values:
      - values/traefik-default-certificate-store.yaml.gotmpl
      - global:
          labels:
            app.kubernetes.io/part-of: traefik
          annotations:
            argocd.argoproj.io/sync-wave: "2"
