repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

apiVersions:
  - "networking.k8s.io/v1/IngressClass"

values:
  - default-certificate:
      enabled: true

releases:
  - name: traefik
    namespace: traefik
    chart: traefik/traefik
    version: "~10"
    missingFileHandler: Warn
    values:
      - values/traefik.yaml

  - name: traefik-default-certificate
    namespace: traefik
    chart: ../../charts/cert-manager-tls
    condition: default-certificate.enabled
    missingFileHandler: Warn
    values:
      - values/traefik-default-certificate.yaml.gotmpl

  - name: traefik-default-certificate-store
    namespace: traefik
    chart: ../../charts/traefik-ingress
    condition: default-certificate.enabled
    missingFileHandler: Warn
    values:
      - values/traefik-default-certificate-store.yaml
