repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: metrics-server
    namespace: metrics-server
    chart: bitnami/metrics-server
    version: "~5"
    missingFileHandler: Warn
    values:
      - values/metrics-server.yaml
