apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pomerium-signing-key
    namespace: pomerium
spec:
    suspend: false
    secretTemplates:
        - name: pomerium-signing-key
          stringData:
            signing-key: ENC[AES256_GCM,data:bZzWmnIqmol7xYfAVm868GEzL2KNtDsrgX3BdqLYUBpGoCaDda0e/btL/0M6yPaSCb0Gl9I+QMJx74F+z1D09eQEzDZ6vYHxLU3qz8Wdkelq77AdZ5t2ZDMRVZSYHvLYn5Y/Wc+OCuoFaJovLShKiBbb9SytnTdXWi73Ab8kuMciQOxuxNTHI0Ur4KYR8LJK8sty4HszcBnYIr4mMkPmHV5eh3E5R0JHcXchogGEh9OI/sBRW2CLUCbgpNPW7KwyD7VuLbmghJDjONY5z+bqyKLi8bOJIVu0Nzu7/Tg76unSrAHeQm72DNEjzX1DyPxSgn8qduxGZNdrOiiwAHr8El075qx6Z1DELV9+Sl//6luqFw+JRB0nLF77AQcN1fDAL9HIyzYLwzbe1i9lMB5lBVc=,iv:tyQHmr4P22r7mPDgZ9sklilFDgCAAZgAbEfPGjXkMPE=,tag:UTIFp7S+Z5NOZ6bEtOdVgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdGxyWGUyZHlteHBJVDNj
            ZkFmQW1wOGVRQWkxeWdhdytiQ1YvUVpjRWlFCmhsOFZKdVovTGZVeW9ta2t2b3E3
            R1JtWDdvblhVOFZyOUR1d1ZRSVJtMVUKLS0tIHZCLzBsZGhFN0t4S1Bxd1VMaW1X
            ZnlYMDhzU1R0MWNFalF1QU1UZTZPMkkKa04nzRC0fB56lcrUKXCMOSR0kVBWGBSt
            pkysmxJFAit2rm1zB/dadPbtQYHcLEZX8EZbTuUKk2nTppl5dY7hfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-02T03:01:02Z"
    mac: ENC[AES256_GCM,data:SCOO+XKAPNmxcKt/dQqCUvrRde96m6LvIu2uqnoGj6RKwXd+5gQL3BX9T/sGOexSyfwv0yRuQXxKq2kO1C8PkEii+/vVfdnTOyLOajUzk4wtrvmRcMiWWXMdv3/xDw3MGUr5+ep+2cn6FuXwR8xOdBimjrtYQzkSkzSOJbWRt1o=,iv:0zp2oseb4fFts14gBHUUT17PVosDgoC1bzHRSo+H0Vc=,tag:P73gKMWjpHcuIV8kP6Ok9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
