apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pomerium-shared-env
    namespace: pomerium
spec:
    suspend: false
    secretTemplates:
        - name: pomerium-shared-env
          stringData:
            SHARED_SECRET: ENC[AES256_GCM,data:unseXNJHYG6K3NY2LROpPm3/E0W76EUBxYDQALyOI+Z2TYz6m7PvYvNQDd4=,iv:1mmy3actaHnjo+6aZROJDjBby34HkR6LTaRetoW1vyA=,tag:WifRABMCcwWw5XWfh+hu8g==,type:str]
            COOKIE_SECRET: ENC[AES256_GCM,data:HchikQ1xTQDGtomqVOiXVwgSsTuaa5QIuCEG2JO7zpBBGnNTYv4WZAqYgpk=,iv:673LP3k85xIotIOsWavFb4oM7f5ZtUO21dLTFE5n+G0=,tag:MigC8GrW9nLXhKvpAldnbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMmE3Q1ViVnkyWWJJOUVw
            SkRERkdXbnNYN3JWNUVDMFY4T0lzMVJKSUM0CjVnSlQvWW95MjgyZVF6a0lMbTlP
            cWFXOGpId3JaY3FmTHRsUXdrdE12R1UKLS0tIHpRT2FWMnovTCszSXN5VXNIcHpC
            M2hYZ0RNV1QzUnBJODdXUmY3L3c4ZlkKwWj2Dtk87LNIJZtKBqWl4yxQjakHq8+2
            DSu5po5Z2vinMhuCDf0Mo1GSKYy7o+ddWSZ5fY5gx2K2lk4xldKO9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-10-31T00:44:07Z"
    mac: ENC[AES256_GCM,data:aajmWE/s6YMXWaryg2Jv0pSW5kzWY31C+YnqIyKKtDraZIdvZ4qon/fckJUxSHI/BnMXHP/iRZ9VvrBwpsSL5TwPqpA7xOuWNQdEWcIZyd3nEetDFjM7XNmY7RQCyf/l5Ug/iHJo+TjAQ7hDEiAqQyCzazyHavx7hbe1Kzj98Dc=,iv:jfQDJzQoNa2B3jh0J4Gja4NyZdD1O10RzsXFx0KFVwc=,tag:hhZUeBbg4+ysp4t/J6X0nQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
