apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pomerium-shared-env
    namespace: pomerium
spec:
    suspend: false
    secretTemplates:
        - name: pomerium-shared-env
          stringData:
            SHARED_SECRET: ENC[AES256_GCM,data:unseXNJHYG6K3NY2LROpPm3/E0W76EUBxYDQALyOI+Z2TYz6m7PvYvNQDd4=,iv:1mmy3actaHnjo+6aZROJDjBby34HkR6LTaRetoW1vyA=,tag:WifRABMCcwWw5XWfh+hu8g==,type:str]
            COOKIE_SECRET: ENC[AES256_GCM,data:HchikQ1xTQDGtomqVOiXVwgSsTuaa5QIuCEG2JO7zpBBGnNTYv4WZAqYgpk=,iv:673LP3k85xIotIOsWavFb4oM7f5ZtUO21dLTFE5n+G0=,tag:MigC8GrW9nLXhKvpAldnbw==,type:str]
            IDP_CLIENT_SECRET: ENC[AES256_GCM,data:r1kI5NgZdNUoj8ejiV65D+bSb8Ctq2qQUqvHylefdkU9DNgp0W0WmA==,iv:WgmbhRRd7B8ddOn9yhcWbjlib7cslZvSS2xwCHP9YpU=,tag:BT3PmXfZTQHFk541zWutDQ==,type:str]
            IDP_CLIENT_ID: ENC[AES256_GCM,data:q3e7BUJXZ1lbsG2QXcAft2W+q2c=,iv:0WE9JvBnDHjhgQAMLAPJEkH0f2xodIMGjjFUDkI4MxU=,tag:L5CKvpb7qF4j2oAbnEclYw==,type:str]
            IDP_SERVICE_ACCOUNT: ENC[AES256_GCM,data:iCuhf0PMQuqzPdIuDkEk3te0KY+D9LCkQskhUPoxjeYh9gpH3MAhNGczntghLjRq82djrh+dmNG9IwKxxPJZAKB9DhBl2p0BGST59T/h/MWGoFaF/JJrAZqJd/IaYPO51yX+zBw9zglWrba/eu27VrYJlZtmBik0Gy7/XUrpwO0=,iv:7R8WpfQe0Gn0BOyV68ygCQH6ECVZPEgrJSsroZVpveo=,tag:GqMmxvp+s6PVoCtTOd0Inw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMmE3Q1ViVnkyWWJJOUVw
            SkRERkdXbnNYN3JWNUVDMFY4T0lzMVJKSUM0CjVnSlQvWW95MjgyZVF6a0lMbTlP
            cWFXOGpId3JaY3FmTHRsUXdrdE12R1UKLS0tIHpRT2FWMnovTCszSXN5VXNIcHpC
            M2hYZ0RNV1QzUnBJODdXUmY3L3c4ZlkKwWj2Dtk87LNIJZtKBqWl4yxQjakHq8+2
            DSu5po5Z2vinMhuCDf0Mo1GSKYy7o+ddWSZ5fY5gx2K2lk4xldKO9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-02T02:48:29Z"
    mac: ENC[AES256_GCM,data:WeE4Jcl26a0A2WfbdiFUby34hNq2YGFKYogo5RsZRcKJdWiEQ5qux1PVmg5PBbCWjZxiUI2F60yAsMDNyQHlWJtbDasGBsUNAOGy5qtkqivMuzrm/9IAJZa4caeTJxaamfHsbNeaempaqULYYAKkXFDu8Zy5TTy0DYLPUogaIJo=,iv:W58Dqe/xZFMCQumL4nDcJzq0npyWaxiBhbDx9H8/08c=,tag:OCMVEd9HbLgJLKX8BlylaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
