apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pomerium-redis-credentials
    namespace: pomerium
spec:
    suspend: false
    secretTemplates:
        - name: pomerium-redis-credentials
          stringData:
            password: ENC[AES256_GCM,data:Y1XlonhtIG/j/ZZzxca/OKeJYWE1ei18VhI2vsxHdCg=,iv:wnRmJL4B28HrUWmOZLFD66KsMhlJSk+dHdv7ifohFNo=,tag:eZhyiAP0+goNbyc03+kJbQ==,type:str]
            DATABROKER_STORAGE_CONNECTION_STRING: ENC[AES256_GCM,data:YoCLmRKV8vtTBCRJ2BSB75oSPur5Ll3rIL4rmHkimBh3u61jv2BVGDENKrJs+6vEMW1pgueXjLHH1gbIPI7P/jigwff9nNPW9CBB08WzeB8MmViVL9vRVU/8HLHQNOyH,iv:k6xIfON3M9ADUCSIZgrnwIpT+2BeGD9cER/62Ajpgbw=,tag:o6Y6Po/PUeTsAC8rYctcpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bkVRenZSUzRlcDJkZGZO
            SU5ucSs4YXFsRlNqWnlqWUZ3QisvN3JKRjNNCmZ6ZTJaQmNvOFBVeW5SbUJleUJP
            OERkd3hwWEZ2TEp0NXNLc29yUm8zQlEKLS0tIDRkT3ZsZzJrQkJ3SGtXS2ZHUldH
            Wm5IVXRpZTBHeGMrR1RCbWF0MXVEVGsK1pflddzSrjgLO2v0PO1Q2QloaB9KQsku
            Is8Pxz1rYIBsYkTAMl2xujpkPzqtByCfDWFiV9/QcKNHN4HTZ461YA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-02T03:20:25Z"
    mac: ENC[AES256_GCM,data:ovaO4LLtNsGdK6Plf7CD3Vm/t7tvJ8Ln5RoE/81mR5QNIhLbn2ND2W+mKI1OyDIZZD/g8XzpEx6jr3hjFQsAYLBpQnuoPMxzeH1NCBCohRMuVGqZAfUq5UTmk/tpTbS+cQ7j9uN5naTg6wGFu9iISztTseff4/eN4wAZEbA6rTM=,iv:nfafS37oaraRJ+KyHkJAqZ3fpT/YJSFKNZdUFF8Ha0c=,tag:+kABjl18UFJJmhlOJBw8nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
