---
# Source: cert-manager-tls/templates/issuer.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pomerium-ca
  namespace: pomerium
  labels:
    helm.sh/chart: cert-manager-tls-1.1.0
    app.kubernetes.io/name: pomerium-ca
    app.kubernetes.io/instance: pomerium-tls
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ca:
    secretName: pomerium-ca-tls
---
# Source: cert-manager-tls/templates/issuer.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: pomerium-selfsigned
  namespace: pomerium
  labels:
    helm.sh/chart: cert-manager-tls-1.1.0
    app.kubernetes.io/name: pomerium-selfsigned
    app.kubernetes.io/instance: pomerium-tls
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selfSigned: {}
