kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
pushgateway:
  enabled: false

server:
  image:
    tag: v2.31.0

  extraArgs:
    storage.tsdb.retention.size: 540GB

  persistentVolume:
    storageClass: ceph-block
    size: 600Gi
