---
# Source: pomerium/charts/redis/templates/master/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pomerium-redis-master
  namespace: "pomerium"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-14.7.2
    app.kubernetes.io/instance: pomerium
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: pomerium
      app.kubernetes.io/component: master
  serviceName: pomerium-redis-headless
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        helm.sh/chart: redis-14.7.2
        app.kubernetes.io/instance: pomerium
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: master
      annotations:
        checksum/configmap: 0e8c0a64b6955521b8fdfcddd371be1e6a74ac9cb0ff48ddd5cd0ea2cd61af24
        checksum/health: bd1b7a0e60568113e185c194305fe5a9cfe57bd382d517452b4ad4df708cf08e
        checksum/scripts: a0f9168a6225ed5cf4b72ff914ee25f0101f1d67d5f367a3b8ff5e2f80d563dc
        checksum/secret: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    spec:
      
      securityContext:
        fsGroup: 1001
      serviceAccountName: pomerium-redis
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: redis
                    app.kubernetes.io/instance: pomerium
                    app.kubernetes.io/component: master
                namespaces:
                  - "pomerium"
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      terminationGracePeriodSeconds: 30
      containers:
        - name: redis
          image: docker.io/bitnami/redis:6.2.4-debian-10-r13
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          command:
            - /bin/bash
          args:
            - -c
            - /opt/bitnami/scripts/start-scripts/start-master.sh
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: REDIS_REPLICATION_MODE
              value: master
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: REDIS_TLS_ENABLED
              value: "yes"
            - name: REDIS_TLS_PORT
              value: "6379"
            - name:  REDIS_TLS_AUTH_CLIENTS
              value: "yes"
            - name:  REDIS_TLS_CERT_FILE
              value: /opt/bitnami/redis/certs/tls.crt
            - name:  REDIS_TLS_KEY_FILE
              value: /opt/bitnami/redis/certs/tls.key
            - name:  REDIS_TLS_CA_FILE
              value: /opt/bitnami/redis/certs/ca.crt
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: 6
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_liveness_local.sh 5
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 5
            exec:
              command:
                - sh
                - -c
                - /health/ping_readiness_local.sh 1
          resources:
            limits: {}
            requests: {}
          volumeMounts:
            - name: start-scripts
              mountPath: /opt/bitnami/scripts/start-scripts
            - name: health
              mountPath: /health
            - name: redis-data
              mountPath: /data
              subPath: 
            - name: config
              mountPath: /opt/bitnami/redis/mounted-etc
            - name: redis-tmp-conf
              mountPath: /opt/bitnami/redis/etc/
            - name: tmp
              mountPath: /tmp
            - name: redis-certificates
              mountPath: /opt/bitnami/redis/certs
              readOnly: true
      volumes:
        - name: start-scripts
          configMap:
            name: pomerium-redis-scripts
            defaultMode: 0755
        - name: health
          configMap:
            name: pomerium-redis-health
            defaultMode: 0755
        - name: config
          configMap:
            name: pomerium-redis-configuration
        - name: redis-tmp-conf
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: redis-certificates
          secret:
            secretName: pomerium-redis-tls
            defaultMode: 256
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/instance: pomerium
          app.kubernetes.io/component: master
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "8Gi"
