apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-env
    namespace: grafana
spec:
    suspend: false
    secretTemplates:
        - name: grafana-env
          stringData:
            GF_AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:sUTlaF9W/RUP3pMjkwnGPL6fhxk=,iv:vp0YqYDdcvbtjNGq+S+RvmCUZWSzFl1GXcJBZ9tnM1o=,tag:70JEIdylfpGQdv1k21sLSw==,type:str]
            GF_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:ANE7Gdm+hwd21nFV7tADD8E4MvM/UqWhb0uik+bOcE+RiLdqo5xQhg==,iv:27jNI/J0Istoh9Xu9lGlq6DVJHp1rPqbrtmg7zL1Sb4=,tag:ZREiqD+FzgxaZZLZb0IidQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVEZiWUF5UDlWdkpCeDVv
            S25MbVZwU0FnOTVabDBSOXBUWkM5MjZWcDBvCjcweUZkK3JyR1hsRk5sNHRwZys4
            bllLbytLS3Q3ZWtlVmpOT1lycHp5S0kKLS0tIERSV0VOSTBxWFo1WWhGNG1JZnNx
            dTBjV0JoZ1Y4aHI0Z0hIdHNiTk9IUTAKGDLVtySIS27xYd9j/ziT/S0/xvgmhM8D
            qWftxLE4Cu6voOr5YLQ81pCWwyI7sGWLiOZrdTvGkYcbPu4ePmXA6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-04T06:14:16Z"
    mac: ENC[AES256_GCM,data:Wwxf3RwWMO44lkc+lbr9HgXhIBPTKcuHDtdYFK83AWha11he1nwb7mliNPZ0Z/lefPpW2zV09Qt9WEwJvOUqz2S82lCegmSK6n/CftAziw6ov2iD/yuHG5ByitaM/HNKOyd9EXqCJG1HGDSwdbGjHDHiwjduOyR/K3rYFtJCPCk=,iv:0sLA3Hpt25ETnaZ7saQEkLozoXMvQT19ZP3eCHuBiJo=,tag:EHBrB1N/15lRvkXx/eY81g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
