apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-env
    namespace: grafana
spec:
    suspend: false
    secretTemplates:
        - name: grafana-env
          stringData:
            GRAFANA_AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:rBb1rKnh/iF6LI/Rq573fvdtXnA=,iv:zyDy2dzqLrMdUq0hzkbyU8h7gPbb71EG9rYAYZs/Rb4=,tag:66URNDNeGJ8a6mb4CWdcuA==,type:str]
            GRAFANA_AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:xqhyyX7LmzzZcJzeUocVmF8Fu/881IcrK6Q0mhkyo7QsFfOj/MGKrw==,iv:sxmXW/uK3zaLR1+AGiuBMkfryQaFmJ8ca5WAmVVLILM=,tag:soTu6Ow5dw0b1YVjA1kiXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVEZiWUF5UDlWdkpCeDVv
            S25MbVZwU0FnOTVabDBSOXBUWkM5MjZWcDBvCjcweUZkK3JyR1hsRk5sNHRwZys4
            bllLbytLS3Q3ZWtlVmpOT1lycHp5S0kKLS0tIERSV0VOSTBxWFo1WWhGNG1JZnNx
            dTBjV0JoZ1Y4aHI0Z0hIdHNiTk9IUTAKGDLVtySIS27xYd9j/ziT/S0/xvgmhM8D
            qWftxLE4Cu6voOr5YLQ81pCWwyI7sGWLiOZrdTvGkYcbPu4ePmXA6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-04T01:54:20Z"
    mac: ENC[AES256_GCM,data:/cLwqPE+EQz8vRYCgPt5YWHiwX0FUaPCUdxB/4nsRDZmrqw+8eDCWFBgp3BZaA9lrjv6/40r4jp1eHjv0+CRWQB+XYnI/vhDN+PlvJ56A2/hbir+rS0vBr4+Z6XMWq4pm4H1pq5SRUaoQMNSNvbyK/hj6hHIJn+1kBx+/FzTL8I=,iv:53fN/Nczj0Nxs4YoZ6WSkOqVGqBoTdFjw5JnOnr2j5E=,tag:YLdto2j+SIm0R4f9zijLLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
