apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-admin-credentials
    namespace: grafana
spec:
    suspend: false
    secretTemplates:
        - name: grafana-admin-credentials
          type: kubernetes.io/basic-auth
          stringData:
            username: ENC[AES256_GCM,data:KtSkluKQw8F6//pdd4pfnju1,iv:P0Fwo7MzKMc5iNkfevEX/PRcoPomiiU1Gq8GWdSEUS8=,tag:mLkmzD235TWEIVOs4JjE8g==,type:str]
            password: ENC[AES256_GCM,data:8PeJVnkAHblpevm5Ugd4wbjLf2jiGbYhSu9AjfY2zsd+WGSn4xCzbUhKit6VFU8bnBmwwIk4roPcz8I8,iv:z9p5EWakaI+UKD3VA2nr0+uwjAvyloesMhXB6D4DLXw=,tag:y74RyIKpDaOpVLLjy3pOJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w99lxq32x7psm5r6xmuescavezsszm4wcqpl48rcu5yj2nkk5s4qgnepp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbTJwN3pBQkVnWVhNLzZU
            VHFwbDdyNVI5VHp3Mi9RQWtId0pvaTF0Z2g0Cm0zbTJpa0REU1cxVWF1dlpFcDNY
            NXlSMFc1ZVRYbXJYMlR0cThpaW9WTWMKLS0tIFFMT2ZuL293NmRneDkrSHVtbFYz
            bTRCNjhiaXI1QjVDdUoyc1IyUzd4alkKmCRmvVoIbexhi9pCCRgatiy8fhDa44Rc
            0JcJT0fJM9uR2NvC/hXOD75som7TBnNiTPNfAN7MnbMi2MPWxTEFUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-04T06:05:12Z"
    mac: ENC[AES256_GCM,data:kUn2lLWVgLFnDTCKaEvk0fH5Zow0JYnQrdrPUlH1/ep7qkXMcMCRbTk9V6Ho9N57UkEWNxwRDeHr2kuzo83j4gC2HgsjzKWDIhzBEdF6/4juE5GRPYfdwRlMg5O7BuKwGqNpgCnt77PMz+Tttl3nbv0u2MBi9erHEQG+CSCli8g=,iv:2WP81KjP6mkWoE5aoatpz4CkPqIs2enRrYrLe967F1c=,tag:8U0oA5NnvXquadyljbjGOQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
