---
# Source: minecraft/templates/minecraft-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: adventure-minecraft
  labels:
    app: adventure-minecraft
    chart: "minecraft-3.6.3"
    release: "adventure"
    heritage: "Helm"
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
  - name: minecraft
    port: 25565
    targetPort: minecraft
    protocol: TCP
  selector:
    app: adventure-minecraft
