---
# Source: minecraft/templates/rcon-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: "adventure-minecraft-rcon"
  annotations:
    {}
  labels:
    app: adventure-minecraft
    chart: "minecraft-3.5.0"
    release: "adventure"
    heritage: "Helm"
spec:
  type: ClusterIP
  ports:
  - name: rcon
    port: 25575
    targetPort: rcon
    protocol: TCP
  selector:
    app: adventure-minecraft
