---
# Source: cert-manager-webhook-dnsimple/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.acme.thedixon.net
  labels:
    app: cert-manager-webhook-dnsimple
    chart: cert-manager-webhook-dnsimple-0.1.1
    release: cert-manager-webhook-dnsimple
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-dnsimple-webhook-tls"
spec:
  group: acme.thedixon.net
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-dnsimple
    namespace: cert-manager
  version: v1alpha1
