---
# Source: cert-manager-webhook-dnsimple/templates/pki.yaml
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-dnsimple-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-dnsimple
    chart: cert-manager-webhook-dnsimple-0.1.1
    release: cert-manager-webhook-dnsimple
    heritage: Helm
spec:
  secretName: cert-manager-webhook-dnsimple-ca
  duration: 43800h0m0s # 5y
  issuerRef:
    name: cert-manager-webhook-dnsimple-selfsign
  commonName: "ca.dnsimple-webhook.cert-manager"
  isCA: true
---
# Source: cert-manager-webhook-dnsimple/templates/pki.yaml
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-manager-webhook-dnsimple-webhook-tls
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-dnsimple
    chart: cert-manager-webhook-dnsimple-0.1.1
    release: cert-manager-webhook-dnsimple
    heritage: Helm
spec:
  secretName: cert-manager-webhook-dnsimple-webhook-tls
  duration: 8760h0m0s # 1y
  issuerRef:
    name: cert-manager-webhook-dnsimple-ca
  dnsNames:
  - cert-manager-webhook-dnsimple
  - cert-manager-webhook-dnsimple.cert-manager
  - cert-manager-webhook-dnsimple.cert-manager.svc
---
# Source: cert-manager-webhook-dnsimple/templates/pki.yaml
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-dnsimple-selfsign
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-dnsimple
    chart: cert-manager-webhook-dnsimple-0.1.1
    release: cert-manager-webhook-dnsimple
    heritage: Helm
spec:
  selfSigned: {}
---
# Source: cert-manager-webhook-dnsimple/templates/pki.yaml
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-manager-webhook-dnsimple-ca
  namespace: "cert-manager"
  labels:
    app: cert-manager-webhook-dnsimple
    chart: cert-manager-webhook-dnsimple-0.1.1
    release: cert-manager-webhook-dnsimple
    heritage: Helm
spec:
  ca:
    secretName: cert-manager-webhook-dnsimple-ca
