repositories:
  - name: minecraft
    url: https://itzg.github.io/minecraft-server-charts/
  - name: moopholo
    url: https://helm.monetact.net
  - name: bedag
    url: https://bedag.github.io/helm-charts/

releases:
  - name: velocity
    namespace: minecraft
    chart: moopholo/velocity
    version: "~0.3"
    missingFileHandler: Warn
    values:
      - values/velocity.yaml

  - name: minecraft-ingress
    namespace: minecraft
    chart: moopholo/traefik-custom-resources
    version: "~2.0.7"
    missingFileHandler: Warn
    values:
      - values/minecraft-ingress.yaml

  - name: config-patches
    namespace: minecraft
    chart: bedag/raw
    version: "1.1.0"
    missingFileHandler: Warn
    values:
      - values/config-patches.yaml.gotmpl

  - name: adventure
    namespace: minecraft
    chart: minecraft/minecraft
    version: "~3.6"
    missingFileHandler: Warn
    values:
      - values/adventure.yaml
