name: Helm
on:
  push:
    paths:
      - charts
  pull_request:
    paths:
      - charts

jobs:
  lint:
    name: runner / lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v1
      - uses: actions/setup-python@v2
      - uses: helm/chart-testing-action@v2.1.0

      - id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - if: steps.list-changed.outputs.changed == 'true'
        run: ct lint
