name: Render Manifests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [master]

jobs:
  find-changes:
    name: runner / set-matrix
    runs-on: ubuntu-latest
    if: github.event_name != 'issue_comment'

    outputs:
      matrix: ${{ steps.changed-apps.outputs.matrix }}
      changes: ${{ steps.changed-apps.outputs.changes }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - id: changed-apps
        run: |
          ./.github/scripts/apps-matrix-output-from-git-diff.sh

  render-changes:
    name: runner / render-manifests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [find-changes]
    if: needs.find-changes.outputs.changes == 'true'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix: ${{ fromJson(needs.find-changes.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
      - uses: albertdixon/helmfile-render@v0
        with:
          app: ${{ matrix.app-name }}

      - uses: docker://ghcr.io/yannh/kubeconform:v0.4.12-alpine
        with:
          args: -n 8 -summary $GITHUB_WORKSPACE/apps/${{ matrix.app-name }}

      - name: Commit Updates
        uses: EndBug/add-and-commit@v7
        with:
          message: "${{ matrix.app-name }}: update manifests"
          add: apps
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
