name: Render Manifests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches: [main]

jobs:
  find-changes:
    name: runner / set-matrix
    runs-on: ubuntu-latest
    if: github.event_name != 'issue_comment'
    permissions:
      contents: read

    outputs:
      matrix: ${{ steps.changed-apps.outputs.matrix }}
      changes: ${{ steps.changed-apps.outputs.changes }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - id: changed-apps
        run: |
          ./.github/scripts/apps-matrix-output-from-git-diff.sh

  render-changes:
    name: runner / render-manifests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [find-changes]
    if: needs.find-changes.outputs.changes == 'true'
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix: ${{ fromJson(needs.find-changes.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - id: render
        uses: moopholo/helmfile-render@v1
        with:
          app: ${{ matrix.app-name }}

      - uses: docker://ghcr.io/yannh/kubeconform:v0.4.12-alpine
        with:
          args: -ignore-missing-schemas -n 8 -summary /github/workspace/apps/${{ matrix.app-name }}/deploy/local

      - name: Commit Updates
        uses: EndBug/add-and-commit@v8.0.2
        with:
          pull: --rebase --autostash
          push: false
          message: "feat(${{ matrix.app-name }}): render ${{ steps.render.outputs.rendered }}"
          default_author: github_actions
          add: apps
      - run: |
          ./.github/scripts/git-push.sh
