---
# Source: snapshot-validation-webhook/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapshot-validation-webhook
  labels:
    helm.sh/chart: snapshot-validation-webhook-1.2.1
    app.kubernetes.io/name: snapshot-validation-webhook
    app.kubernetes.io/instance: snapshot-validation-webhook
    app.kubernetes.io/version: "v4.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: snapshot-validation-webhook
      app.kubernetes.io/instance: snapshot-validation-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snapshot-validation-webhook
        app.kubernetes.io/instance: snapshot-validation-webhook
    spec:
      serviceAccountName: snapshot-validation-webhook
      securityContext:
        {}
      containers:
        - name: snapshot-validation-webhook
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "k8s.gcr.io/sig-storage/snapshot-validation-webhook:v4.2.1"
          imagePullPolicy: IfNotPresent
          args:
            - --tls-private-key-file=/etc/snapshot-validation/tls.key
            - --tls-cert-file=/etc/snapshot-validation/tls.crt
            - --port=8443
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/snapshot-validation
              name: tls-config
          livenessProbe:
            httpGet:
              path: /readyz
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /readyz
              port: https
              scheme: HTTPS
          resources:
            {}
      volumes:
        - name: tls-config
          secret:
            secretName: snapshot-validation-webhook-tls
