---
# Source: snapshot-validation-webhook/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshot-validation-webhook
  labels:
    helm.sh/chart: snapshot-validation-webhook-1.2.1
    app.kubernetes.io/name: snapshot-validation-webhook
    app.kubernetes.io/instance: snapshot-validation-webhook
    app.kubernetes.io/version: "v4.2.1"
    app.kubernetes.io/managed-by: Helm
